Repository oneteme/inspect-app, pull requests merged in 2025-01, with the labels that each got.

#69 screen to view Processes (sessions) running on a server for a specific duration
  src/app/app.module.ts
  src/app/service/router.service.ts
  src/app/service/trace.service.ts
  src/app/shared/pipe/title-case.pipe.ts
  src/app/shared/shared.module.ts
  src/app/views/detail/session/main/detail-session-main.view.html
  src/app/views/detail/session/main/detail-session-main.view.ts
  src/app/views/detail/session/rest/detail-session-rest.view.html
  src/app/views/detail/session/rest/detail-session-rest.view.ts
  src/app/views/dump/dump.view.html
  src/app/views/dump/dump.view.scss
  src/app/views/dump/dump.view.ts
  src/app/views/dump/timeline/dump-timeline.component.ts
  src/app/views/views.module.ts
Labels: enhancement

#76 DateTimePicker on search session view for lower data
  src/app/shared/material/custom-date-adapter.ts
  src/app/shared/material/custom-date-range-selection-strategy.ts
  src/app/shared/material/material.module.ts
  src/app/shared/shared.module.ts
  src/app/views/architecture/architecture.view.ts
  src/app/views/dashboard/dashboard.component.ts
  src/app/views/search/main/search-main.view.html
  src/app/views/search/main/search-main.view.ts
  src/app/views/search/rest/search-rest.view.html
  src/app/views/search/rest/search-rest.view.ts
  src/app/views/statistic/application/statistic-application.view.ts
  src/app/views/statistic/database/statistic-database.view.ts
  src/app/views/statistic/rest/statistic-rest.view.ts
  src/app/views/statistic/user/statistic-user.view.ts
  src/app/views/statistic/view/statistic-client.view.ts
  src/environments/environment.ts
  src/styles.scss
Labels: enhancement

#79 auto tag release
  .github/release.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: enhancement

#80 [Bug] Fixed view bugs related to end value being null
  src/app/model/trace.model.ts
  src/app/shared/pipe/duration.pipe.ts
  src/app/views/detail/session/_component/database-table/detail-database-table.component.html
  src/app/views/detail/session/_component/ftp-table/detail-ftp-table.component.html
  src/app/views/detail/session/_component/ldap-table/detail-ldap-table.component.html
  src/app/views/detail/session/_component/local-table/detail-local-table.component.html
  src/app/views/detail/session/_component/rest-table/detail-rest-table.component.html
  src/app/views/detail/session/_component/smtp-table/detail-smtp-table.component.html
  src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
  src/app/views/detail/session/rest/detail-session-rest.view.ts
  src/styles.scss
Labels: bug

#82 Fix: [inspect-app#67] resolve multiple bugs related to loading in detail session page
  src/app/views/detail/session/_component/detail-session.component.html
  src/app/views/detail/session/_component/detail-session.component.ts
  src/app/views/detail/session/rest/detail-session-rest.view.html
  src/app/views/detail/session/rest/detail-session-rest.view.ts
Labels: bug, enhancement

#84 Fix: resolve multiple bugs related to loading in detail main session page
  src/app/views/detail/session/main/detail-session-main.view.html
  src/app/views/detail/session/main/detail-session-main.view.ts
  src/app/views/detail/session/rest/detail-session-rest.view.html
Labels: bug

#87 Fix: set correct condition for parent loading
  src/app/views/detail/session/rest/detail-session-rest.view.html
  src/app/views/detail/session/rest/detail-session-rest.view.ts
Labels: bug

#88 Fixed bugs related to range DateTimePicker
  src/app/model/conf.model.ts
  src/app/shared/material/custom-date-adapter.ts
  src/app/views/search/main/search-main.view.html
  src/app/views/search/main/search-main.view.ts
  src/app/views/search/rest/search-rest.view.html
  src/app/views/search/rest/search-rest.view.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: bug

#97 Improved timeline component
  src/app/views/detail/session/_component/detail-session.component.html
  src/app/views/detail/session/_component/timeline/detail-timeline.component.html
  src/app/views/detail/session/_component/timeline/detail-timeline.component.ts
  src/styles.scss
Labels: enhancement

#99 Dockerize Web Application and Set Up Continuous Deployment on Docker Hub
  .github/workflows/release.yml
  Dockerfile
  README.md
  angular.json
  docker/config-env.map
  docker/nginx.conf
  docker/rungnx.sh
  package.json
Labels: enhancement

#101 Enhanced the configuration used in the app
  src/app/model/conf.model.ts
  src/app/shared/util.ts
  src/app/views/search/main/search-main.view.ts
  src/app/views/search/rest/search-rest.view.ts
  src/environments/environment.ts
Labels: enhancement

#102 Fixed uncorrect configuration when building in production env
  angular.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: bug

#104 Merge remote config before bootstrapping
  Dockerfile
  src/assets/environement.remote.json
  src/main.ts
Labels: enhancement

#107 Added a dedicated icon for batch nodes in tree view
  src/app/model/tree.model.ts
Labels: enhancement

#108 Added documentation for all application constants in README.md
  README.md
Labels: enhancement
